-- =====================================================================
-- Corrige ColumnName/Name/PrintName a PascalCase en AD_Column y AD_Element
-- para COMUS_TechnicalVisit (AD_Table_ID=1000118).
-- La sincronizacion desde la BD trajo los nombres en minusculas (Postgres
-- pliega los identificadores sin comillas), generando un AD_Element nuevo
-- por cada columna nueva. Cada elemento tocado aqui es exclusivo de esta
-- tabla (verificado: ningun AD_Element_ID se comparte con otra columna del
-- diccionario), por lo que el update no afecta a otras tablas.
-- No se toca la columna fisica en la BD: sigue siendo minuscula (normal en
-- Postgres para identificadores sin comillas) y sigue funcionando igual,
-- igual que ya ocurre con columnas existentes como IsNaturalPerson.
-- =====================================================================

BEGIN;

UPDATE AD_Column SET ColumnName='KoboSubmissionTime', Name='KoboSubmissionTime', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004892;
UPDATE AD_Element SET ColumnName='KoboSubmissionTime', Name='KoboSubmissionTime', PrintName='KoboSubmissionTime', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000897;
UPDATE AD_Column SET ColumnName='RawKoboJSON', Name='RawKoboJSON', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004894;
UPDATE AD_Element SET ColumnName='RawKoboJSON', Name='RawKoboJSON', PrintName='RawKoboJSON', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000898;
UPDATE AD_Column SET ColumnName='UbicacionLatitud', Name='UbicacionLatitud', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004895;
UPDATE AD_Element SET ColumnName='UbicacionLatitud', Name='UbicacionLatitud', PrintName='UbicacionLatitud', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000899;
UPDATE AD_Column SET ColumnName='UbicacionLongitud', Name='UbicacionLongitud', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004896;
UPDATE AD_Element SET ColumnName='UbicacionLongitud', Name='UbicacionLongitud', PrintName='UbicacionLongitud', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000900;
UPDATE AD_Column SET ColumnName='UbicacionAltitud', Name='UbicacionAltitud', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004897;
UPDATE AD_Element SET ColumnName='UbicacionAltitud', Name='UbicacionAltitud', PrintName='UbicacionAltitud', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000901;
UPDATE AD_Column SET ColumnName='UbicacionPrecision', Name='UbicacionPrecision', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004898;
UPDATE AD_Element SET ColumnName='UbicacionPrecision', Name='UbicacionPrecision', PrintName='UbicacionPrecision', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000902;
UPDATE AD_Column SET ColumnName='HoraInicio', Name='HoraInicio', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004899;
UPDATE AD_Element SET ColumnName='HoraInicio', Name='HoraInicio', PrintName='HoraInicio', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000903;
UPDATE AD_Column SET ColumnName='HoraFin', Name='HoraFin', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004900;
UPDATE AD_Element SET ColumnName='HoraFin', Name='HoraFin', PrintName='HoraFin', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000904;
UPDATE AD_Column SET ColumnName='FechaSistema', Name='FechaSistema', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004901;
UPDATE AD_Element SET ColumnName='FechaSistema', Name='FechaSistema', PrintName='FechaSistema', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000905;
UPDATE AD_Column SET ColumnName='UsuarioApp', Name='UsuarioApp', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004902;
UPDATE AD_Element SET ColumnName='UsuarioApp', Name='UsuarioApp', PrintName='UsuarioApp', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000906;
UPDATE AD_Column SET ColumnName='IdDispositivo', Name='IdDispositivo', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004903;
UPDATE AD_Element SET ColumnName='IdDispositivo', Name='IdDispositivo', PrintName='IdDispositivo', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000907;
UPDATE AD_Column SET ColumnName='CodigoProductor', Name='CodigoProductor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004904;
UPDATE AD_Element SET ColumnName='CodigoProductor', Name='CodigoProductor', PrintName='CodigoProductor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000908;
UPDATE AD_Column SET ColumnName='NombreProductor', Name='NombreProductor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004905;
UPDATE AD_Element SET ColumnName='NombreProductor', Name='NombreProductor', PrintName='NombreProductor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000909;
UPDATE AD_Column SET ColumnName='FechaVisita', Name='FechaVisita', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004906;
UPDATE AD_Element SET ColumnName='FechaVisita', Name='FechaVisita', PrintName='FechaVisita', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000910;
UPDATE AD_Column SET ColumnName='Semana', Name='Semana', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004907;
UPDATE AD_Element SET ColumnName='Semana', Name='Semana', PrintName='Semana', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000911;
UPDATE AD_Column SET ColumnName='TipoVisita', Name='TipoVisita', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004908;
UPDATE AD_Element SET ColumnName='TipoVisita', Name='TipoVisita', PrintName='TipoVisita', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000912;
UPDATE AD_Column SET ColumnName='TecnicoResponsable', Name='TecnicoResponsable', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004909;
UPDATE AD_Element SET ColumnName='TecnicoResponsable', Name='TecnicoResponsable', PrintName='TecnicoResponsable', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000913;
UPDATE AD_Column SET ColumnName='ClaveUnica', Name='ClaveUnica', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004910;
UPDATE AD_Element SET ColumnName='ClaveUnica', Name='ClaveUnica', PrintName='ClaveUnica', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000914;
UPDATE AD_Column SET ColumnName='EmpPiso', Name='EmpPiso', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004911;
UPDATE AD_Element SET ColumnName='EmpPiso', Name='EmpPiso', PrintName='EmpPiso', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000915;
UPDATE AD_Column SET ColumnName='EmpPisoPts', Name='EmpPisoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004912;
UPDATE AD_Element SET ColumnName='EmpPisoPts', Name='EmpPisoPts', PrintName='EmpPisoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000916;
UPDATE AD_Column SET ColumnName='EmpMallaSaran', Name='EmpMallaSaran', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004913;
UPDATE AD_Element SET ColumnName='EmpMallaSaran', Name='EmpMallaSaran', PrintName='EmpMallaSaran', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000917;
UPDATE AD_Column SET ColumnName='EmpMallaSaranPts', Name='EmpMallaSaranPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004914;
UPDATE AD_Element SET ColumnName='EmpMallaSaranPts', Name='EmpMallaSaranPts', PrintName='EmpMallaSaranPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000918;
UPDATE AD_Column SET ColumnName='EmpFacilLimpieza', Name='EmpFacilLimpieza', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004915;
UPDATE AD_Element SET ColumnName='EmpFacilLimpieza', Name='EmpFacilLimpieza', PrintName='EmpFacilLimpieza', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000919;
UPDATE AD_Column SET ColumnName='EmpFacilLimpiezaPts', Name='EmpFacilLimpiezaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004916;
UPDATE AD_Element SET ColumnName='EmpFacilLimpiezaPts', Name='EmpFacilLimpiezaPts', PrintName='EmpFacilLimpiezaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000920;
UPDATE AD_Column SET ColumnName='EmpPerimetro', Name='EmpPerimetro', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004917;
UPDATE AD_Element SET ColumnName='EmpPerimetro', Name='EmpPerimetro', PrintName='EmpPerimetro', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000921;
UPDATE AD_Column SET ColumnName='EmpPerimetroPts', Name='EmpPerimetroPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004918;
UPDATE AD_Element SET ColumnName='EmpPerimetroPts', Name='EmpPerimetroPts', PrintName='EmpPerimetroPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000922;
UPDATE AD_Column SET ColumnName='EmpEstructuraMetalica', Name='EmpEstructuraMetalica', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004919;
UPDATE AD_Element SET ColumnName='EmpEstructuraMetalica', Name='EmpEstructuraMetalica', PrintName='EmpEstructuraMetalica', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000923;
UPDATE AD_Column SET ColumnName='EmpEstructuraMetalicaPts', Name='EmpEstructuraMetalicaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004920;
UPDATE AD_Element SET ColumnName='EmpEstructuraMetalicaPts', Name='EmpEstructuraMetalicaPts', PrintName='EmpEstructuraMetalicaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000924;
UPDATE AD_Column SET ColumnName='BqRepisas', Name='BqRepisas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004921;
UPDATE AD_Element SET ColumnName='BqRepisas', Name='BqRepisas', PrintName='BqRepisas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000925;
UPDATE AD_Column SET ColumnName='BqRepisasPts', Name='BqRepisasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004922;
UPDATE AD_Element SET ColumnName='BqRepisasPts', Name='BqRepisasPts', PrintName='BqRepisasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000926;
UPDATE AD_Column SET ColumnName='BqVentilada', Name='BqVentilada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004923;
UPDATE AD_Element SET ColumnName='BqVentilada', Name='BqVentilada', PrintName='BqVentilada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000927;
UPDATE AD_Column SET ColumnName='BqVentiladaPts', Name='BqVentiladaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004924;
UPDATE AD_Element SET ColumnName='BqVentiladaPts', Name='BqVentiladaPts', PrintName='BqVentiladaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000928;
UPDATE AD_Column SET ColumnName='BqBajoLlave', Name='BqBajoLlave', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004925;
UPDATE AD_Element SET ColumnName='BqBajoLlave', Name='BqBajoLlave', PrintName='BqBajoLlave', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000929;
UPDATE AD_Column SET ColumnName='BqBajoLlavePts', Name='BqBajoLlavePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004926;
UPDATE AD_Element SET ColumnName='BqBajoLlavePts', Name='BqBajoLlavePts', PrintName='BqBajoLlavePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000930;
UPDATE AD_Column SET ColumnName='BcPuertaOrden', Name='BcPuertaOrden', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004927;
UPDATE AD_Element SET ColumnName='BcPuertaOrden', Name='BcPuertaOrden', PrintName='BcPuertaOrden', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000931;
UPDATE AD_Column SET ColumnName='BcPuertaOrdenPts', Name='BcPuertaOrdenPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004928;
UPDATE AD_Element SET ColumnName='BcPuertaOrdenPts', Name='BcPuertaOrdenPts', PrintName='BcPuertaOrdenPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000932;
UPDATE AD_Column SET ColumnName='ZmDuchaLavaojos', Name='ZmDuchaLavaojos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004929;
UPDATE AD_Element SET ColumnName='ZmDuchaLavaojos', Name='ZmDuchaLavaojos', PrintName='ZmDuchaLavaojos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000933;
UPDATE AD_Column SET ColumnName='ZmDuchaLavaojosPts', Name='ZmDuchaLavaojosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004930;
UPDATE AD_Element SET ColumnName='ZmDuchaLavaojosPts', Name='ZmDuchaLavaojosPts', PrintName='ZmDuchaLavaojosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000934;
UPDATE AD_Column SET ColumnName='ZmBordeRetencion', Name='ZmBordeRetencion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004931;
UPDATE AD_Element SET ColumnName='ZmBordeRetencion', Name='ZmBordeRetencion', PrintName='ZmBordeRetencion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000935;
UPDATE AD_Column SET ColumnName='ZmBordeRetencionPts', Name='ZmBordeRetencionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004932;
UPDATE AD_Element SET ColumnName='ZmBordeRetencionPts', Name='ZmBordeRetencionPts', PrintName='ZmBordeRetencionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000936;
UPDATE AD_Column SET ColumnName='ZmFosaDescontaminacion', Name='ZmFosaDescontaminacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004933;
UPDATE AD_Element SET ColumnName='ZmFosaDescontaminacion', Name='ZmFosaDescontaminacion', PrintName='ZmFosaDescontaminacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000937;
UPDATE AD_Column SET ColumnName='ZmFosaDescontaminacionPts', Name='ZmFosaDescontaminacionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004934;
UPDATE AD_Element SET ColumnName='ZmFosaDescontaminacionPts', Name='ZmFosaDescontaminacionPts', PrintName='ZmFosaDescontaminacionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000938;
UPDATE AD_Column SET ColumnName='PrPiso', Name='PrPiso', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004935;
UPDATE AD_Element SET ColumnName='PrPiso', Name='PrPiso', PrintName='PrPiso', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000939;
UPDATE AD_Column SET ColumnName='PrPisoPts', Name='PrPisoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004936;
UPDATE AD_Element SET ColumnName='PrPisoPts', Name='PrPisoPts', PrintName='PrPisoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000940;
UPDATE AD_Column SET ColumnName='PrLimpio', Name='PrLimpio', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004937;
UPDATE AD_Element SET ColumnName='PrLimpio', Name='PrLimpio', PrintName='PrLimpio', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000941;
UPDATE AD_Column SET ColumnName='PrLimpioPts', Name='PrLimpioPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004938;
UPDATE AD_Element SET ColumnName='PrLimpioPts', Name='PrLimpioPts', PrintName='PrLimpioPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000942;
UPDATE AD_Column SET ColumnName='PrTecho', Name='PrTecho', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004939;
UPDATE AD_Element SET ColumnName='PrTecho', Name='PrTecho', PrintName='PrTecho', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000943;
UPDATE AD_Column SET ColumnName='PrTechoPts', Name='PrTechoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004940;
UPDATE AD_Element SET ColumnName='PrTechoPts', Name='PrTechoPts', PrintName='PrTechoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000944;
UPDATE AD_Column SET ColumnName='PedAguaClorada', Name='PedAguaClorada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004941;
UPDATE AD_Element SET ColumnName='PedAguaClorada', Name='PedAguaClorada', PrintName='PedAguaClorada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000945;
UPDATE AD_Column SET ColumnName='PedAguaCloradaPts', Name='PedAguaCloradaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004942;
UPDATE AD_Element SET ColumnName='PedAguaCloradaPts', Name='PedAguaCloradaPts', PrintName='PedAguaCloradaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000946;
UPDATE AD_Column SET ColumnName='PedDesague', Name='PedDesague', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004943;
UPDATE AD_Element SET ColumnName='PedDesague', Name='PedDesague', PrintName='PedDesague', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000947;
UPDATE AD_Column SET ColumnName='PedDesaguePts', Name='PedDesaguePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004944;
UPDATE AD_Element SET ColumnName='PedDesaguePts', Name='PedDesaguePts', PrintName='PedDesaguePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000948;
UPDATE AD_Column SET ColumnName='PedIngreso', Name='PedIngreso', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004945;
UPDATE AD_Element SET ColumnName='PedIngreso', Name='PedIngreso', PrintName='PedIngreso', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000949;
UPDATE AD_Column SET ColumnName='PedIngresoPts', Name='PedIngresoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004946;
UPDATE AD_Element SET ColumnName='PedIngresoPts', Name='PedIngresoPts', PrintName='PedIngresoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000950;
UPDATE AD_Column SET ColumnName='FdTapa', Name='FdTapa', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004947;
UPDATE AD_Element SET ColumnName='FdTapa', Name='FdTapa', PrintName='FdTapa', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000951;
UPDATE AD_Column SET ColumnName='FdTapaPts', Name='FdTapaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004948;
UPDATE AD_Element SET ColumnName='FdTapaPts', Name='FdTapaPts', PrintName='FdTapaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000952;
UPDATE AD_Column SET ColumnName='FdLimpia', Name='FdLimpia', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004949;
UPDATE AD_Element SET ColumnName='FdLimpia', Name='FdLimpia', PrintName='FdLimpia', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000953;
UPDATE AD_Column SET ColumnName='FdLimpiaPts', Name='FdLimpiaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004950;
UPDATE AD_Element SET ColumnName='FdLimpiaPts', Name='FdLimpiaPts', PrintName='FdLimpiaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000954;
UPDATE AD_Column SET ColumnName='BanoAgua', Name='BanoAgua', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004951;
UPDATE AD_Element SET ColumnName='BanoAgua', Name='BanoAgua', PrintName='BanoAgua', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000955;
UPDATE AD_Column SET ColumnName='BanoAguaPts', Name='BanoAguaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004952;
UPDATE AD_Element SET ColumnName='BanoAguaPts', Name='BanoAguaPts', PrintName='BanoAguaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000956;
UPDATE AD_Column SET ColumnName='BanoBasurero', Name='BanoBasurero', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004953;
UPDATE AD_Element SET ColumnName='BanoBasurero', Name='BanoBasurero', PrintName='BanoBasurero', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000957;
UPDATE AD_Column SET ColumnName='BanoBasureroPts', Name='BanoBasureroPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004954;
UPDATE AD_Element SET ColumnName='BanoBasureroPts', Name='BanoBasureroPts', PrintName='BanoBasureroPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000958;
UPDATE AD_Column SET ColumnName='BanoPapel', Name='BanoPapel', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004955;
UPDATE AD_Element SET ColumnName='BanoPapel', Name='BanoPapel', PrintName='BanoPapel', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000959;
UPDATE AD_Column SET ColumnName='BanoPapelPts', Name='BanoPapelPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004956;
UPDATE AD_Element SET ColumnName='BanoPapelPts', Name='BanoPapelPts', PrintName='BanoPapelPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000960;
UPDATE AD_Column SET ColumnName='LavAgua', Name='LavAgua', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004957;
UPDATE AD_Element SET ColumnName='LavAgua', Name='LavAgua', PrintName='LavAgua', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000961;
UPDATE AD_Column SET ColumnName='LavAguaPts', Name='LavAguaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004958;
UPDATE AD_Element SET ColumnName='LavAguaPts', Name='LavAguaPts', PrintName='LavAguaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000962;
UPDATE AD_Column SET ColumnName='LavDesague', Name='LavDesague', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004959;
UPDATE AD_Element SET ColumnName='LavDesague', Name='LavDesague', PrintName='LavDesague', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000963;
UPDATE AD_Column SET ColumnName='LavDesaguePts', Name='LavDesaguePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004960;
UPDATE AD_Element SET ColumnName='LavDesaguePts', Name='LavDesaguePts', PrintName='LavDesaguePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000964;
UPDATE AD_Column SET ColumnName='LavJabon', Name='LavJabon', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004961;
UPDATE AD_Element SET ColumnName='LavJabon', Name='LavJabon', PrintName='LavJabon', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000965;
UPDATE AD_Column SET ColumnName='LavJabonPts', Name='LavJabonPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004962;
UPDATE AD_Element SET ColumnName='LavJabonPts', Name='LavJabonPts', PrintName='LavJabonPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000966;
UPDATE AD_Column SET ColumnName='LavToalla', Name='LavToalla', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004963;
UPDATE AD_Element SET ColumnName='LavToalla', Name='LavToalla', PrintName='LavToalla', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000967;
UPDATE AD_Column SET ColumnName='LavToallaPts', Name='LavToallaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004964;
UPDATE AD_Element SET ColumnName='LavToallaPts', Name='LavToallaPts', PrintName='LavToallaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000968;
UPDATE AD_Column SET ColumnName='PuntajeInfraestructura', Name='PuntajeInfraestructura', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004965;
UPDATE AD_Element SET ColumnName='PuntajeInfraestructura', Name='PuntajeInfraestructura', PrintName='PuntajeInfraestructura', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000969;
UPDATE AD_Column SET ColumnName='ELprTanque', Name='ELprTanque', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004966;
UPDATE AD_Element SET ColumnName='ELprTanque', Name='ELprTanque', PrintName='ELprTanque', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000970;
UPDATE AD_Column SET ColumnName='ELprTanquePts', Name='ELprTanquePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004967;
UPDATE AD_Element SET ColumnName='ELprTanquePts', Name='ELprTanquePts', PrintName='ELprTanquePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000971;
UPDATE AD_Column SET ColumnName='ELprTendedero', Name='ELprTendedero', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004968;
UPDATE AD_Element SET ColumnName='ELprTendedero', Name='ELprTendedero', PrintName='ELprTendedero', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000972;
UPDATE AD_Column SET ColumnName='ELprTendederoPts', Name='ELprTendederoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004969;
UPDATE AD_Element SET ColumnName='ELprTendederoPts', Name='ELprTendederoPts', PrintName='ELprTendederoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000973;
UPDATE AD_Column SET ColumnName='ETinasEstado', Name='ETinasEstado', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004970;
UPDATE AD_Element SET ColumnName='ETinasEstado', Name='ETinasEstado', PrintName='ETinasEstado', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000974;
UPDATE AD_Column SET ColumnName='ETinasEstadoPts', Name='ETinasEstadoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004971;
UPDATE AD_Element SET ColumnName='ETinasEstadoPts', Name='ETinasEstadoPts', PrintName='ETinasEstadoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000975;
UPDATE AD_Column SET ColumnName='ETinasNumero', Name='ETinasNumero', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004972;
UPDATE AD_Element SET ColumnName='ETinasNumero', Name='ETinasNumero', PrintName='ETinasNumero', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000976;
UPDATE AD_Column SET ColumnName='ETinasNumeroPts', Name='ETinasNumeroPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004973;
UPDATE AD_Element SET ColumnName='ETinasNumeroPts', Name='ETinasNumeroPts', PrintName='ETinasNumeroPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000977;
UPDATE AD_Column SET ColumnName='EBalanzaEstado', Name='EBalanzaEstado', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004974;
UPDATE AD_Element SET ColumnName='EBalanzaEstado', Name='EBalanzaEstado', PrintName='EBalanzaEstado', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000978;
UPDATE AD_Column SET ColumnName='EBalanzaEstadoPts', Name='EBalanzaEstadoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004975;
UPDATE AD_Element SET ColumnName='EBalanzaEstadoPts', Name='EBalanzaEstadoPts', PrintName='EBalanzaEstadoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000979;
UPDATE AD_Column SET ColumnName='EBalanzaCalibrada', Name='EBalanzaCalibrada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004976;
UPDATE AD_Element SET ColumnName='EBalanzaCalibrada', Name='EBalanzaCalibrada', PrintName='EBalanzaCalibrada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000980;
UPDATE AD_Column SET ColumnName='EBalanzaCalibradaPts', Name='EBalanzaCalibradaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004977;
UPDATE AD_Element SET ColumnName='EBalanzaCalibradaPts', Name='EBalanzaCalibradaPts', PrintName='EBalanzaCalibradaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000981;
UPDATE AD_Column SET ColumnName='EPlatosEstado', Name='EPlatosEstado', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004978;
UPDATE AD_Element SET ColumnName='EPlatosEstado', Name='EPlatosEstado', PrintName='EPlatosEstado', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000982;
UPDATE AD_Column SET ColumnName='EPlatosEstadoPts', Name='EPlatosEstadoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004979;
UPDATE AD_Element SET ColumnName='EPlatosEstadoPts', Name='EPlatosEstadoPts', PrintName='EPlatosEstadoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000983;
UPDATE AD_Column SET ColumnName='EPlatosProtectores', Name='EPlatosProtectores', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004980;
UPDATE AD_Element SET ColumnName='EPlatosProtectores', Name='EPlatosProtectores', PrintName='EPlatosProtectores', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000984;
UPDATE AD_Column SET ColumnName='EPlatosProtectoresPts', Name='EPlatosProtectoresPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004981;
UPDATE AD_Element SET ColumnName='EPlatosProtectoresPts', Name='EPlatosProtectoresPts', PrintName='EPlatosProtectoresPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000985;
UPDATE AD_Column SET ColumnName='ECalibrador', Name='ECalibrador', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004982;
UPDATE AD_Element SET ColumnName='ECalibrador', Name='ECalibrador', PrintName='ECalibrador', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000986;
UPDATE AD_Column SET ColumnName='ECalibradorPts', Name='ECalibradorPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004983;
UPDATE AD_Element SET ColumnName='ECalibradorPts', Name='ECalibradorPts', PrintName='ECalibradorPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000987;
UPDATE AD_Column SET ColumnName='EMesaAcolchada', Name='EMesaAcolchada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004984;
UPDATE AD_Element SET ColumnName='EMesaAcolchada', Name='EMesaAcolchada', PrintName='EMesaAcolchada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000988;
UPDATE AD_Column SET ColumnName='EMesaAcolchadaPts', Name='EMesaAcolchadaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004985;
UPDATE AD_Element SET ColumnName='EMesaAcolchadaPts', Name='EMesaAcolchadaPts', PrintName='EMesaAcolchadaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000989;
UPDATE AD_Column SET ColumnName='EMesaFacilLimpieza', Name='EMesaFacilLimpieza', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004986;
UPDATE AD_Element SET ColumnName='EMesaFacilLimpieza', Name='EMesaFacilLimpieza', PrintName='EMesaFacilLimpieza', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000990;
UPDATE AD_Column SET ColumnName='EMesaFacilLimpiezaPts', Name='EMesaFacilLimpiezaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004987;
UPDATE AD_Element SET ColumnName='EMesaFacilLimpiezaPts', Name='EMesaFacilLimpiezaPts', PrintName='EMesaFacilLimpiezaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000991;
UPDATE AD_Column SET ColumnName='EDosificadores', Name='EDosificadores', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004988;
UPDATE AD_Element SET ColumnName='EDosificadores', Name='EDosificadores', PrintName='EDosificadores', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000992;
UPDATE AD_Column SET ColumnName='EDosificadoresPts', Name='EDosificadoresPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004989;
UPDATE AD_Element SET ColumnName='EDosificadoresPts', Name='EDosificadoresPts', PrintName='EDosificadoresPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000993;
UPDATE AD_Column SET ColumnName='PuntajeEquipos', Name='PuntajeEquipos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004990;
UPDATE AD_Element SET ColumnName='PuntajeEquipos', Name='PuntajeEquipos', PrintName='PuntajeEquipos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000994;
UPDATE AD_Column SET ColumnName='HRacimosColgadero', Name='HRacimosColgadero', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004991;
UPDATE AD_Element SET ColumnName='HRacimosColgadero', Name='HRacimosColgadero', PrintName='HRacimosColgadero', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000995;
UPDATE AD_Column SET ColumnName='HRacimosColgaderoPts', Name='HRacimosColgaderoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004992;
UPDATE AD_Element SET ColumnName='HRacimosColgaderoPts', Name='HRacimosColgaderoPts', PrintName='HRacimosColgaderoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000996;
UPDATE AD_Column SET ColumnName='HCultivoSinBasura', Name='HCultivoSinBasura', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004993;
UPDATE AD_Element SET ColumnName='HCultivoSinBasura', Name='HCultivoSinBasura', PrintName='HCultivoSinBasura', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000997;
UPDATE AD_Column SET ColumnName='HCultivoSinBasuraPts', Name='HCultivoSinBasuraPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004994;
UPDATE AD_Element SET ColumnName='HCultivoSinBasuraPts', Name='HCultivoSinBasuraPts', PrintName='HCultivoSinBasuraPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000998;
UPDATE AD_Column SET ColumnName='HCultivoSinAnimales', Name='HCultivoSinAnimales', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004995;
UPDATE AD_Element SET ColumnName='HCultivoSinAnimales', Name='HCultivoSinAnimales', PrintName='HCultivoSinAnimales', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1000999;
UPDATE AD_Column SET ColumnName='HCultivoSinAnimalesPts', Name='HCultivoSinAnimalesPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004996;
UPDATE AD_Element SET ColumnName='HCultivoSinAnimalesPts', Name='HCultivoSinAnimalesPts', PrintName='HCultivoSinAnimalesPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001000;
UPDATE AD_Column SET ColumnName='HCultivoSinVertidos', Name='HCultivoSinVertidos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004997;
UPDATE AD_Element SET ColumnName='HCultivoSinVertidos', Name='HCultivoSinVertidos', PrintName='HCultivoSinVertidos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001001;
UPDATE AD_Column SET ColumnName='HCultivoSinVertidosPts', Name='HCultivoSinVertidosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004998;
UPDATE AD_Element SET ColumnName='HCultivoSinVertidosPts', Name='HCultivoSinVertidosPts', PrintName='HCultivoSinVertidosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001002;
UPDATE AD_Column SET ColumnName='HSinRaquis', Name='HSinRaquis', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1004999;
UPDATE AD_Element SET ColumnName='HSinRaquis', Name='HSinRaquis', PrintName='HSinRaquis', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001003;
UPDATE AD_Column SET ColumnName='HSinRaquisPts', Name='HSinRaquisPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005000;
UPDATE AD_Element SET ColumnName='HSinRaquisPts', Name='HSinRaquisPts', PrintName='HSinRaquisPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001004;
UPDATE AD_Column SET ColumnName='HRetiroRestos', Name='HRetiroRestos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005001;
UPDATE AD_Element SET ColumnName='HRetiroRestos', Name='HRetiroRestos', PrintName='HRetiroRestos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001005;
UPDATE AD_Column SET ColumnName='HRetiroRestosPts', Name='HRetiroRestosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005002;
UPDATE AD_Element SET ColumnName='HRetiroRestosPts', Name='HRetiroRestosPts', PrintName='HRetiroRestosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001006;
UPDATE AD_Column SET ColumnName='HEnvasesTripleLavado', Name='HEnvasesTripleLavado', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005003;
UPDATE AD_Element SET ColumnName='HEnvasesTripleLavado', Name='HEnvasesTripleLavado', PrintName='HEnvasesTripleLavado', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001007;
UPDATE AD_Column SET ColumnName='HEnvasesTripleLavadoPts', Name='HEnvasesTripleLavadoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005004;
UPDATE AD_Element SET ColumnName='HEnvasesTripleLavadoPts', Name='HEnvasesTripleLavadoPts', PrintName='HEnvasesTripleLavadoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001008;
UPDATE AD_Column SET ColumnName='HEmpacadoraLimpia', Name='HEmpacadoraLimpia', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005005;
UPDATE AD_Element SET ColumnName='HEmpacadoraLimpia', Name='HEmpacadoraLimpia', PrintName='HEmpacadoraLimpia', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001009;
UPDATE AD_Column SET ColumnName='HEmpacadoraLimpiaPts', Name='HEmpacadoraLimpiaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005006;
UPDATE AD_Element SET ColumnName='HEmpacadoraLimpiaPts', Name='HEmpacadoraLimpiaPts', PrintName='HEmpacadoraLimpiaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001010;
UPDATE AD_Column SET ColumnName='HEmpacadoraSinAnimales', Name='HEmpacadoraSinAnimales', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005007;
UPDATE AD_Element SET ColumnName='HEmpacadoraSinAnimales', Name='HEmpacadoraSinAnimales', PrintName='HEmpacadoraSinAnimales', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001011;
UPDATE AD_Column SET ColumnName='HEmpacadoraSinAnimalesPts', Name='HEmpacadoraSinAnimalesPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005008;
UPDATE AD_Element SET ColumnName='HEmpacadoraSinAnimalesPts', Name='HEmpacadoraSinAnimalesPts', PrintName='HEmpacadoraSinAnimalesPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001012;
UPDATE AD_Column SET ColumnName='HInmediacionesLimpias', Name='HInmediacionesLimpias', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005009;
UPDATE AD_Element SET ColumnName='HInmediacionesLimpias', Name='HInmediacionesLimpias', PrintName='HInmediacionesLimpias', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001013;
UPDATE AD_Column SET ColumnName='HInmediacionesLimpiasPts', Name='HInmediacionesLimpiasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005010;
UPDATE AD_Element SET ColumnName='HInmediacionesLimpiasPts', Name='HInmediacionesLimpiasPts', PrintName='HInmediacionesLimpiasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001014;
UPDATE AD_Column SET ColumnName='HCloracionCorrecta', Name='HCloracionCorrecta', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005011;
UPDATE AD_Element SET ColumnName='HCloracionCorrecta', Name='HCloracionCorrecta', PrintName='HCloracionCorrecta', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001015;
UPDATE AD_Column SET ColumnName='HCloracionCorrectaPts', Name='HCloracionCorrectaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005012;
UPDATE AD_Element SET ColumnName='HCloracionCorrectaPts', Name='HCloracionCorrectaPts', PrintName='HCloracionCorrectaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001016;
UPDATE AD_Column SET ColumnName='HMaterialesPalets', Name='HMaterialesPalets', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005013;
UPDATE AD_Element SET ColumnName='HMaterialesPalets', Name='HMaterialesPalets', PrintName='HMaterialesPalets', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001017;
UPDATE AD_Column SET ColumnName='HMaterialesPaletsPts', Name='HMaterialesPaletsPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005014;
UPDATE AD_Element SET ColumnName='HMaterialesPaletsPts', Name='HMaterialesPaletsPts', PrintName='HMaterialesPaletsPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001018;
UPDATE AD_Column SET ColumnName='HFrutaPalets', Name='HFrutaPalets', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005015;
UPDATE AD_Element SET ColumnName='HFrutaPalets', Name='HFrutaPalets', PrintName='HFrutaPalets', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001019;
UPDATE AD_Column SET ColumnName='HFrutaPaletsPts', Name='HFrutaPaletsPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005016;
UPDATE AD_Element SET ColumnName='HFrutaPaletsPts', Name='HFrutaPaletsPts', PrintName='HFrutaPaletsPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001020;
UPDATE AD_Column SET ColumnName='HCarpetaActualizada', Name='HCarpetaActualizada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005017;
UPDATE AD_Element SET ColumnName='HCarpetaActualizada', Name='HCarpetaActualizada', PrintName='HCarpetaActualizada', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001021;
UPDATE AD_Column SET ColumnName='HCarpetaActualizadaPts', Name='HCarpetaActualizadaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005018;
UPDATE AD_Element SET ColumnName='HCarpetaActualizadaPts', Name='HCarpetaActualizadaPts', PrintName='HCarpetaActualizadaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001022;
UPDATE AD_Column SET ColumnName='HEppGeneral', Name='HEppGeneral', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005019;
UPDATE AD_Element SET ColumnName='HEppGeneral', Name='HEppGeneral', PrintName='HEppGeneral', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001023;
UPDATE AD_Column SET ColumnName='HEppGeneralPts', Name='HEppGeneralPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005020;
UPDATE AD_Element SET ColumnName='HEppGeneralPts', Name='HEppGeneralPts', PrintName='HEppGeneralPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001024;
UPDATE AD_Column SET ColumnName='HEppTinas', Name='HEppTinas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005021;
UPDATE AD_Element SET ColumnName='HEppTinas', Name='HEppTinas', PrintName='HEppTinas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001025;
UPDATE AD_Column SET ColumnName='HEppTinasPts', Name='HEppTinasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005022;
UPDATE AD_Element SET ColumnName='HEppTinasPts', Name='HEppTinasPts', PrintName='HEppTinasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001026;
UPDATE AD_Column SET ColumnName='HEppEnfunde', Name='HEppEnfunde', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005023;
UPDATE AD_Element SET ColumnName='HEppEnfunde', Name='HEppEnfunde', PrintName='HEppEnfunde', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001027;
UPDATE AD_Column SET ColumnName='HEppEnfundePts', Name='HEppEnfundePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005024;
UPDATE AD_Element SET ColumnName='HEppEnfundePts', Name='HEppEnfundePts', PrintName='HEppEnfundePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001028;
UPDATE AD_Column SET ColumnName='HUsanLavamanos', Name='HUsanLavamanos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005025;
UPDATE AD_Element SET ColumnName='HUsanLavamanos', Name='HUsanLavamanos', PrintName='HUsanLavamanos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001029;
UPDATE AD_Column SET ColumnName='HUsanLavamanosPts', Name='HUsanLavamanosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005026;
UPDATE AD_Element SET ColumnName='HUsanLavamanosPts', Name='HUsanLavamanosPts', PrintName='HUsanLavamanosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001030;
UPDATE AD_Column SET ColumnName='HAreaAlimentos', Name='HAreaAlimentos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005027;
UPDATE AD_Element SET ColumnName='HAreaAlimentos', Name='HAreaAlimentos', PrintName='HAreaAlimentos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001031;
UPDATE AD_Column SET ColumnName='HAreaAlimentosPts', Name='HAreaAlimentosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005028;
UPDATE AD_Element SET ColumnName='HAreaAlimentosPts', Name='HAreaAlimentosPts', PrintName='HAreaAlimentosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001032;
UPDATE AD_Column SET ColumnName='HSinAccesorios', Name='HSinAccesorios', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005029;
UPDATE AD_Element SET ColumnName='HSinAccesorios', Name='HSinAccesorios', PrintName='HSinAccesorios', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001033;
UPDATE AD_Column SET ColumnName='HSinAccesoriosPts', Name='HSinAccesoriosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005030;
UPDATE AD_Element SET ColumnName='HSinAccesoriosPts', Name='HSinAccesoriosPts', PrintName='HSinAccesoriosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001034;
UPDATE AD_Column SET ColumnName='HBotiquinExtintor', Name='HBotiquinExtintor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005031;
UPDATE AD_Element SET ColumnName='HBotiquinExtintor', Name='HBotiquinExtintor', PrintName='HBotiquinExtintor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001035;
UPDATE AD_Column SET ColumnName='HBotiquinExtintorPts', Name='HBotiquinExtintorPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005032;
UPDATE AD_Element SET ColumnName='HBotiquinExtintorPts', Name='HBotiquinExtintorPts', PrintName='HBotiquinExtintorPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001036;
UPDATE AD_Column SET ColumnName='PuntajeHigiene', Name='PuntajeHigiene', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005033;
UPDATE AD_Element SET ColumnName='PuntajeHigiene', Name='PuntajeHigiene', PrintName='PuntajeHigiene', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001037;
UPDATE AD_Column SET ColumnName='PcPhRango', Name='PcPhRango', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005034;
UPDATE AD_Element SET ColumnName='PcPhRango', Name='PcPhRango', PrintName='PcPhRango', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001038;
UPDATE AD_Column SET ColumnName='PcPhRangoPts', Name='PcPhRangoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005035;
UPDATE AD_Element SET ColumnName='PcPhRangoPts', Name='PcPhRangoPts', PrintName='PcPhRangoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001039;
UPDATE AD_Column SET ColumnName='PcTinaFruta', Name='PcTinaFruta', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005036;
UPDATE AD_Element SET ColumnName='PcTinaFruta', Name='PcTinaFruta', PrintName='PcTinaFruta', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001040;
UPDATE AD_Column SET ColumnName='PcTinaFrutaPts', Name='PcTinaFrutaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005037;
UPDATE AD_Element SET ColumnName='PcTinaFrutaPts', Name='PcTinaFrutaPts', PrintName='PcTinaFrutaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001041;
UPDATE AD_Column SET ColumnName='PcCambioAgua', Name='PcCambioAgua', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005038;
UPDATE AD_Element SET ColumnName='PcCambioAgua', Name='PcCambioAgua', PrintName='PcCambioAgua', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001042;
UPDATE AD_Column SET ColumnName='PcCambioAguaPts', Name='PcCambioAguaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005039;
UPDATE AD_Element SET ColumnName='PcCambioAguaPts', Name='PcCambioAguaPts', PrintName='PcCambioAguaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001043;
UPDATE AD_Column SET ColumnName='PcPlatos', Name='PcPlatos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005040;
UPDATE AD_Element SET ColumnName='PcPlatos', Name='PcPlatos', PrintName='PcPlatos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001044;
UPDATE AD_Column SET ColumnName='PcPlatosPts', Name='PcPlatosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005041;
UPDATE AD_Element SET ColumnName='PcPlatosPts', Name='PcPlatosPts', PrintName='PcPlatosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001045;
UPDATE AD_Column SET ColumnName='PcSaneo', Name='PcSaneo', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005042;
UPDATE AD_Element SET ColumnName='PcSaneo', Name='PcSaneo', PrintName='PcSaneo', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001046;
UPDATE AD_Column SET ColumnName='PcSaneoPts', Name='PcSaneoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005043;
UPDATE AD_Element SET ColumnName='PcSaneoPts', Name='PcSaneoPts', PrintName='PcSaneoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001047;
UPDATE AD_Column SET ColumnName='PcEsquineros', Name='PcEsquineros', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005044;
UPDATE AD_Element SET ColumnName='PcEsquineros', Name='PcEsquineros', PrintName='PcEsquineros', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001048;
UPDATE AD_Column SET ColumnName='PcEsquinerosPts', Name='PcEsquinerosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005045;
UPDATE AD_Element SET ColumnName='PcEsquinerosPts', Name='PcEsquinerosPts', PrintName='PcEsquinerosPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001049;
UPDATE AD_Column SET ColumnName='PcInmersion', Name='PcInmersion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005046;
UPDATE AD_Element SET ColumnName='PcInmersion', Name='PcInmersion', PrintName='PcInmersion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001050;
UPDATE AD_Column SET ColumnName='PcInmersionPts', Name='PcInmersionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005047;
UPDATE AD_Element SET ColumnName='PcInmersionPts', Name='PcInmersionPts', PrintName='PcInmersionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001051;
UPDATE AD_Column SET ColumnName='PcDosificacion', Name='PcDosificacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005048;
UPDATE AD_Element SET ColumnName='PcDosificacion', Name='PcDosificacion', PrintName='PcDosificacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001052;
UPDATE AD_Column SET ColumnName='PcDosificacionPts', Name='PcDosificacionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005049;
UPDATE AD_Element SET ColumnName='PcDosificacionPts', Name='PcDosificacionPts', PrintName='PcDosificacionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001053;
UPDATE AD_Column SET ColumnName='PcAspersor', Name='PcAspersor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005050;
UPDATE AD_Element SET ColumnName='PcAspersor', Name='PcAspersor', PrintName='PcAspersor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001054;
UPDATE AD_Column SET ColumnName='PcAspersorPts', Name='PcAspersorPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005051;
UPDATE AD_Element SET ColumnName='PcAspersorPts', Name='PcAspersorPts', PrintName='PcAspersorPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001055;
UPDATE AD_Column SET ColumnName='PcAspersion', Name='PcAspersion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005052;
UPDATE AD_Element SET ColumnName='PcAspersion', Name='PcAspersion', PrintName='PcAspersion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001056;
UPDATE AD_Column SET ColumnName='PcAspersionPts', Name='PcAspersionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005053;
UPDATE AD_Element SET ColumnName='PcAspersionPts', Name='PcAspersionPts', PrintName='PcAspersionPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001057;
UPDATE AD_Column SET ColumnName='PuntajePostcosecha', Name='PuntajePostcosecha', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005054;
UPDATE AD_Element SET ColumnName='PuntajePostcosecha', Name='PuntajePostcosecha', PrintName='PuntajePostcosecha', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001058;
UPDATE AD_Column SET ColumnName='CajasEvaluadas', Name='CajasEvaluadas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005055;
UPDATE AD_Element SET ColumnName='CajasEvaluadas', Name='CajasEvaluadas', PrintName='CajasEvaluadas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001059;
UPDATE AD_Column SET ColumnName='CajasDanoMecanico', Name='CajasDanoMecanico', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005056;
UPDATE AD_Element SET ColumnName='CajasDanoMecanico', Name='CajasDanoMecanico', PrintName='CajasDanoMecanico', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001060;
UPDATE AD_Column SET ColumnName='CajasDanoInsectos', Name='CajasDanoInsectos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005057;
UPDATE AD_Element SET ColumnName='CajasDanoInsectos', Name='CajasDanoInsectos', PrintName='CajasDanoInsectos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001061;
UPDATE AD_Column SET ColumnName='CajasDanoHongos', Name='CajasDanoHongos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005058;
UPDATE AD_Element SET ColumnName='CajasDanoHongos', Name='CajasDanoHongos', PrintName='CajasDanoHongos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001062;
UPDATE AD_Column SET ColumnName='CajasPresenciaInsectos', Name='CajasPresenciaInsectos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005059;
UPDATE AD_Element SET ColumnName='CajasPresenciaInsectos', Name='CajasPresenciaInsectos', PrintName='CajasPresenciaInsectos', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001063;
UPDATE AD_Column SET ColumnName='GradoColorCorrecto', Name='GradoColorCorrecto', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005060;
UPDATE AD_Element SET ColumnName='GradoColorCorrecto', Name='GradoColorCorrecto', PrintName='GradoColorCorrecto', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001064;
UPDATE AD_Column SET ColumnName='TotalNoConformidades', Name='TotalNoConformidades', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005061;
UPDATE AD_Element SET ColumnName='TotalNoConformidades', Name='TotalNoConformidades', PrintName='TotalNoConformidades', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001065;
UPDATE AD_Column SET ColumnName='AgSinThrips', Name='AgSinThrips', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005062;
UPDATE AD_Element SET ColumnName='AgSinThrips', Name='AgSinThrips', PrintName='AgSinThrips', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001066;
UPDATE AD_Column SET ColumnName='AgSinThripsPts', Name='AgSinThripsPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005063;
UPDATE AD_Element SET ColumnName='AgSinThripsPts', Name='AgSinThripsPts', PrintName='AgSinThripsPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001067;
UPDATE AD_Column SET ColumnName='AgSinPulgon', Name='AgSinPulgon', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005064;
UPDATE AD_Element SET ColumnName='AgSinPulgon', Name='AgSinPulgon', PrintName='AgSinPulgon', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001068;
UPDATE AD_Column SET ColumnName='AgSinPulgonPts', Name='AgSinPulgonPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005065;
UPDATE AD_Element SET ColumnName='AgSinPulgonPts', Name='AgSinPulgonPts', PrintName='AgSinPulgonPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001069;
UPDATE AD_Column SET ColumnName='AgSinCochinilla', Name='AgSinCochinilla', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005066;
UPDATE AD_Element SET ColumnName='AgSinCochinilla', Name='AgSinCochinilla', PrintName='AgSinCochinilla', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001070;
UPDATE AD_Column SET ColumnName='AgSinCochinillaPts', Name='AgSinCochinillaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005067;
UPDATE AD_Element SET ColumnName='AgSinCochinillaPts', Name='AgSinCochinillaPts', PrintName='AgSinCochinillaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001071;
UPDATE AD_Column SET ColumnName='AgSinHormigas', Name='AgSinHormigas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005068;
UPDATE AD_Element SET ColumnName='AgSinHormigas', Name='AgSinHormigas', PrintName='AgSinHormigas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001072;
UPDATE AD_Column SET ColumnName='AgSinHormigasPts', Name='AgSinHormigasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005069;
UPDATE AD_Element SET ColumnName='AgSinHormigasPts', Name='AgSinHormigasPts', PrintName='AgSinHormigasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001073;
UPDATE AD_Column SET ColumnName='AgSinPuntaCigarro', Name='AgSinPuntaCigarro', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005070;
UPDATE AD_Element SET ColumnName='AgSinPuntaCigarro', Name='AgSinPuntaCigarro', PrintName='AgSinPuntaCigarro', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001074;
UPDATE AD_Column SET ColumnName='AgSinPuntaCigarroPts', Name='AgSinPuntaCigarroPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005071;
UPDATE AD_Element SET ColumnName='AgSinPuntaCigarroPts', Name='AgSinPuntaCigarroPts', PrintName='AgSinPuntaCigarroPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001075;
UPDATE AD_Column SET ColumnName='AgSinFusariumR4', Name='AgSinFusariumR4', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005072;
UPDATE AD_Element SET ColumnName='AgSinFusariumR4', Name='AgSinFusariumR4', PrintName='AgSinFusariumR4', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001076;
UPDATE AD_Column SET ColumnName='AgSinFusariumR4Pts', Name='AgSinFusariumR4Pts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005073;
UPDATE AD_Element SET ColumnName='AgSinFusariumR4Pts', Name='AgSinFusariumR4Pts', PrintName='AgSinFusariumR4Pts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001077;
UPDATE AD_Column SET ColumnName='AgSinMoko', Name='AgSinMoko', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005074;
UPDATE AD_Element SET ColumnName='AgSinMoko', Name='AgSinMoko', PrintName='AgSinMoko', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001078;
UPDATE AD_Column SET ColumnName='AgSinMokoPts', Name='AgSinMokoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005075;
UPDATE AD_Element SET ColumnName='AgSinMokoPts', Name='AgSinMokoPts', PrintName='AgSinMokoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001079;
UPDATE AD_Column SET ColumnName='AgSinSigatoka', Name='AgSinSigatoka', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005076;
UPDATE AD_Element SET ColumnName='AgSinSigatoka', Name='AgSinSigatoka', PrintName='AgSinSigatoka', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001080;
UPDATE AD_Column SET ColumnName='AgSinSigatokaPts', Name='AgSinSigatokaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005077;
UPDATE AD_Element SET ColumnName='AgSinSigatokaPts', Name='AgSinSigatokaPts', PrintName='AgSinSigatokaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001081;
UPDATE AD_Column SET ColumnName='AgControlMaleza', Name='AgControlMaleza', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005078;
UPDATE AD_Element SET ColumnName='AgControlMaleza', Name='AgControlMaleza', PrintName='AgControlMaleza', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001082;
UPDATE AD_Column SET ColumnName='AgControlMalezaPts', Name='AgControlMalezaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005079;
UPDATE AD_Element SET ColumnName='AgControlMalezaPts', Name='AgControlMalezaPts', PrintName='AgControlMalezaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001083;
UPDATE AD_Column SET ColumnName='AgDeshoje', Name='AgDeshoje', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005080;
UPDATE AD_Element SET ColumnName='AgDeshoje', Name='AgDeshoje', PrintName='AgDeshoje', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001084;
UPDATE AD_Column SET ColumnName='AgDeshojePts', Name='AgDeshojePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005081;
UPDATE AD_Element SET ColumnName='AgDeshojePts', Name='AgDeshojePts', PrintName='AgDeshojePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001085;
UPDATE AD_Column SET ColumnName='AgDeshije', Name='AgDeshije', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005082;
UPDATE AD_Element SET ColumnName='AgDeshije', Name='AgDeshije', PrintName='AgDeshije', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001086;
UPDATE AD_Column SET ColumnName='AgDeshijePts', Name='AgDeshijePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005083;
UPDATE AD_Element SET ColumnName='AgDeshijePts', Name='AgDeshijePts', PrintName='AgDeshijePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001087;
UPDATE AD_Column SET ColumnName='AgDeschante', Name='AgDeschante', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005084;
UPDATE AD_Element SET ColumnName='AgDeschante', Name='AgDeschante', PrintName='AgDeschante', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001088;
UPDATE AD_Column SET ColumnName='AgDeschantePts', Name='AgDeschantePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005085;
UPDATE AD_Element SET ColumnName='AgDeschantePts', Name='AgDeschantePts', PrintName='AgDeschantePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001089;
UPDATE AD_Column SET ColumnName='AgDestalle', Name='AgDestalle', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005086;
UPDATE AD_Element SET ColumnName='AgDestalle', Name='AgDestalle', PrintName='AgDestalle', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001090;
UPDATE AD_Column SET ColumnName='AgDestallePts', Name='AgDestallePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005087;
UPDATE AD_Element SET ColumnName='AgDestallePts', Name='AgDestallePts', PrintName='AgDestallePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001091;
UPDATE AD_Column SET ColumnName='AgResiembra', Name='AgResiembra', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005088;
UPDATE AD_Element SET ColumnName='AgResiembra', Name='AgResiembra', PrintName='AgResiembra', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001092;
UPDATE AD_Column SET ColumnName='AgResiembraPts', Name='AgResiembraPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005089;
UPDATE AD_Element SET ColumnName='AgResiembraPts', Name='AgResiembraPts', PrintName='AgResiembraPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001093;
UPDATE AD_Column SET ColumnName='AgCintaCorrecta', Name='AgCintaCorrecta', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005090;
UPDATE AD_Element SET ColumnName='AgCintaCorrecta', Name='AgCintaCorrecta', PrintName='AgCintaCorrecta', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001094;
UPDATE AD_Column SET ColumnName='AgCintaCorrectaPts', Name='AgCintaCorrectaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005091;
UPDATE AD_Element SET ColumnName='AgCintaCorrectaPts', Name='AgCintaCorrectaPts', PrintName='AgCintaCorrectaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001095;
UPDATE AD_Column SET ColumnName='AgRacimosDaypas', Name='AgRacimosDaypas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005092;
UPDATE AD_Element SET ColumnName='AgRacimosDaypas', Name='AgRacimosDaypas', PrintName='AgRacimosDaypas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001096;
UPDATE AD_Column SET ColumnName='AgRacimosDaypasPts', Name='AgRacimosDaypasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005093;
UPDATE AD_Element SET ColumnName='AgRacimosDaypasPts', Name='AgRacimosDaypasPts', PrintName='AgRacimosDaypasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001097;
UPDATE AD_Column SET ColumnName='AgDeschiveDesflore', Name='AgDeschiveDesflore', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005094;
UPDATE AD_Element SET ColumnName='AgDeschiveDesflore', Name='AgDeschiveDesflore', PrintName='AgDeschiveDesflore', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001098;
UPDATE AD_Column SET ColumnName='AgDeschiveDesflorePts', Name='AgDeschiveDesflorePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005095;
UPDATE AD_Element SET ColumnName='AgDeschiveDesflorePts', Name='AgDeschiveDesflorePts', PrintName='AgDeschiveDesflorePts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001099;
UPDATE AD_Column SET ColumnName='AgControlHormigas', Name='AgControlHormigas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005096;
UPDATE AD_Element SET ColumnName='AgControlHormigas', Name='AgControlHormigas', PrintName='AgControlHormigas', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001100;
UPDATE AD_Column SET ColumnName='AgControlHormigasPts', Name='AgControlHormigasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005097;
UPDATE AD_Element SET ColumnName='AgControlHormigasPts', Name='AgControlHormigasPts', PrintName='AgControlHormigasPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001101;
UPDATE AD_Column SET ColumnName='AgControlSigatoka', Name='AgControlSigatoka', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005098;
UPDATE AD_Element SET ColumnName='AgControlSigatoka', Name='AgControlSigatoka', PrintName='AgControlSigatoka', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001102;
UPDATE AD_Column SET ColumnName='AgControlSigatokaPts', Name='AgControlSigatokaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005099;
UPDATE AD_Element SET ColumnName='AgControlSigatokaPts', Name='AgControlSigatokaPts', PrintName='AgControlSigatokaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001103;
UPDATE AD_Column SET ColumnName='AgFertilizo', Name='AgFertilizo', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005100;
UPDATE AD_Element SET ColumnName='AgFertilizo', Name='AgFertilizo', PrintName='AgFertilizo', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001104;
UPDATE AD_Column SET ColumnName='AgFertilizoPts', Name='AgFertilizoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005101;
UPDATE AD_Element SET ColumnName='AgFertilizoPts', Name='AgFertilizoPts', PrintName='AgFertilizoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001105;
UPDATE AD_Column SET ColumnName='AgPlanDefinido', Name='AgPlanDefinido', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005102;
UPDATE AD_Element SET ColumnName='AgPlanDefinido', Name='AgPlanDefinido', PrintName='AgPlanDefinido', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001106;
UPDATE AD_Column SET ColumnName='AgPlanDefinidoPts', Name='AgPlanDefinidoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005103;
UPDATE AD_Element SET ColumnName='AgPlanDefinidoPts', Name='AgPlanDefinidoPts', PrintName='AgPlanDefinidoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001107;
UPDATE AD_Column SET ColumnName='AgFertilizoFinca', Name='AgFertilizoFinca', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005104;
UPDATE AD_Element SET ColumnName='AgFertilizoFinca', Name='AgFertilizoFinca', PrintName='AgFertilizoFinca', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001108;
UPDATE AD_Column SET ColumnName='AgFertilizoFincaPts', Name='AgFertilizoFincaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005105;
UPDATE AD_Element SET ColumnName='AgFertilizoFincaPts', Name='AgFertilizoFincaPts', PrintName='AgFertilizoFincaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001109;
UPDATE AD_Column SET ColumnName='AgEnraizamiento', Name='AgEnraizamiento', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005106;
UPDATE AD_Element SET ColumnName='AgEnraizamiento', Name='AgEnraizamiento', PrintName='AgEnraizamiento', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001110;
UPDATE AD_Column SET ColumnName='AgEnraizamientoPts', Name='AgEnraizamientoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005107;
UPDATE AD_Element SET ColumnName='AgEnraizamientoPts', Name='AgEnraizamientoPts', PrintName='AgEnraizamientoPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001111;
UPDATE AD_Column SET ColumnName='AgFertilizacionEdafica', Name='AgFertilizacionEdafica', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005108;
UPDATE AD_Element SET ColumnName='AgFertilizacionEdafica', Name='AgFertilizacionEdafica', PrintName='AgFertilizacionEdafica', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001112;
UPDATE AD_Column SET ColumnName='AgFertilizacionEdaficaPts', Name='AgFertilizacionEdaficaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005109;
UPDATE AD_Element SET ColumnName='AgFertilizacionEdaficaPts', Name='AgFertilizacionEdaficaPts', PrintName='AgFertilizacionEdaficaPts', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001113;
UPDATE AD_Column SET ColumnName='TipoPlanFertilizacion', Name='TipoPlanFertilizacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005110;
UPDATE AD_Element SET ColumnName='TipoPlanFertilizacion', Name='TipoPlanFertilizacion', PrintName='TipoPlanFertilizacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001114;
UPDATE AD_Column SET ColumnName='ProductosFertilizacion', Name='ProductosFertilizacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005111;
UPDATE AD_Element SET ColumnName='ProductosFertilizacion', Name='ProductosFertilizacion', PrintName='ProductosFertilizacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001115;
UPDATE AD_Column SET ColumnName='NumeroFasesFertilizacion', Name='NumeroFasesFertilizacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005112;
UPDATE AD_Element SET ColumnName='NumeroFasesFertilizacion', Name='NumeroFasesFertilizacion', PrintName='NumeroFasesFertilizacion', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001116;
UPDATE AD_Column SET ColumnName='FechaLimiteCumplimiento', Name='FechaLimiteCumplimiento', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005113;
UPDATE AD_Element SET ColumnName='FechaLimiteCumplimiento', Name='FechaLimiteCumplimiento', PrintName='FechaLimiteCumplimiento', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001117;
UPDATE AD_Column SET ColumnName='PuntajeAgricola', Name='PuntajeAgricola', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005114;
UPDATE AD_Element SET ColumnName='PuntajeAgricola', Name='PuntajeAgricola', PrintName='PuntajeAgricola', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001118;
UPDATE AD_Column SET ColumnName='CalificacionAgricola', Name='CalificacionAgricola', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005115;
UPDATE AD_Element SET ColumnName='CalificacionAgricola', Name='CalificacionAgricola', PrintName='CalificacionAgricola', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001119;
UPDATE AD_Column SET ColumnName='PuntajeGlobal', Name='PuntajeGlobal', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005116;
UPDATE AD_Element SET ColumnName='PuntajeGlobal', Name='PuntajeGlobal', PrintName='PuntajeGlobal', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001120;
UPDATE AD_Column SET ColumnName='PorcentajeGlobal', Name='PorcentajeGlobal', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005117;
UPDATE AD_Element SET ColumnName='PorcentajeGlobal', Name='PorcentajeGlobal', PrintName='PorcentajeGlobal', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001121;
UPDATE AD_Column SET ColumnName='Observaciones', Name='Observaciones', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005118;
UPDATE AD_Element SET ColumnName='Observaciones', Name='Observaciones', PrintName='Observaciones', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001122;
UPDATE AD_Column SET ColumnName='Recomendaciones', Name='Recomendaciones', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005119;
UPDATE AD_Element SET ColumnName='Recomendaciones', Name='Recomendaciones', PrintName='Recomendaciones', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001123;
UPDATE AD_Column SET ColumnName='FotoEvidencia', Name='FotoEvidencia', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005120;
UPDATE AD_Element SET ColumnName='FotoEvidencia', Name='FotoEvidencia', PrintName='FotoEvidencia', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001124;
UPDATE AD_Column SET ColumnName='ProductorPresente', Name='ProductorPresente', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005121;
UPDATE AD_Element SET ColumnName='ProductorPresente', Name='ProductorPresente', PrintName='ProductorPresente', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001125;
UPDATE AD_Column SET ColumnName='NombreFirmante', Name='NombreFirmante', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005122;
UPDATE AD_Element SET ColumnName='NombreFirmante', Name='NombreFirmante', PrintName='NombreFirmante', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001126;
UPDATE AD_Column SET ColumnName='FirmaProductor', Name='FirmaProductor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005123;
UPDATE AD_Element SET ColumnName='FirmaProductor', Name='FirmaProductor', PrintName='FirmaProductor', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001127;
UPDATE AD_Column SET ColumnName='MotivoSinFirma', Name='MotivoSinFirma', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Column_ID=1005124;
UPDATE AD_Element SET ColumnName='MotivoSinFirma', Name='MotivoSinFirma', PrintName='MotivoSinFirma', Updated=statement_timestamp(), UpdatedBy=0 WHERE AD_Element_ID=1001128;

COMMIT;
